const links = {
  Design: {
    FlatUI: 'https://flatuicolors.com/',
    '0to255': 'https://0to255.com/',
    IconMonstr: 'https://iconmonstr.com/',
    TablerIcons: 'https://tablericons.com/',
    CodingInventory: 'https://coding.garden/videos/#/?filter=inventory',
    GrowthDesign: 'https://djangopackages.org/',
    'Device Mockups': 'https://techsini.com/multi-mockup/',
    'Blush Design': 'https://blush.design/',
    'Social Media Sizes': 'https://socialsizes.io/',
    UiDesignDaily: 'https://www.uidesigndaily.com/',
    Triangify: 'https://trianglify.io/',
    'Neumorphism.io': 'https://neumorphism.io',
    ClipPathMaker: 'https://bennettfeely.com/clippy/',
    FontJoy: 'https://fontjoy.com/',
    HeroPatterns: 'https://www.heropatterns.com/',
    'CSS Section Separator Maker': 'https://wweb.dev/resources/css-separator-generator',
    'Colour from image': 'https://html-color-codes.info/colors-from-image/',
    'Box Shadow Maker': 'https://cssmatic.com/box-shadow',
    'CSS Gradients': 'https://cssgradient.io',
    Shoelace: 'https://shoelace.style/',
    RemoveBG: 'https://www.remove.bg/',
    'Gymnasium Design Course': 'https://thegymnasium.com/',
    'Nice Page Design Inspo': 'https://nicepage.com/',
    'CSS Grid Generator': 'https://grid.layoutit.com/',
    Lightbox: 'https://lokeshdhakar.com/projects/lightbox2/',
    Swup: 'https://swup.js.org/',
    '3D Book CSS': 'https://3dbook.xyz/',
    LottieAnimations: 'https://airbnb.io/lottie/#/web',
    SVGpathMaker: 'https://codepen.io/anthonydugois/pen/mewdyZ?editors=0010',
  },
  Styles: {
    ChakraUI: 'https://chakra-ui.com/',
    Tailwind: 'https://tailwindcss.com/',
    CSSinJS: 'https://cssinjs.org/?v=v10.4.0',
    'Styled-Components': 'https://styled-components.com/',
    'CSS-Tricks': 'https://css-tricks.com/',
  },
  Tools: {
    VuePress: 'https://vuepress.vuejs.org/',
    ViteJS: 'https://vitejs.dev/',
    WebDevMeasure: 'https://web.dev/measure/',
    ChooseLicense: 'https://choosealicense.com/',
    JSONtoTS: 'http://www.json2ts.com/',
    Wagtail: 'https://www.educative.io/explore',
    Caniuse: 'https://caniuse.com/',
    'Github To CDN Converter': 'https://statically.io/convert/',
    Gitlab: 'https://gitlab.com/',
    Supabase: 'https://app.supabase.io/',
    FormSpree: 'https://formspree.io',
    'Favicon Generator': 'https://www.favicon-generator.org/',
    'Favicon.io': 'https://favicon.io/',
  },
  SupportOthers: {
    WomenWhoStream: 'https://womenwhostream.tech/',
    UnbreakTech: 'https://unbreak.tech/',
    WomenWhoDesign: 'https://womenwho.design/',
    GoogleEngineeringReviews: 'https://google.github.io/eng-practices/',
  },
  Hosting: {
    Netlify: 'https://app.netlify.com',
    Surge: 'https://surge.sh/',
    DigitalOcean: 'https://www.digitalocean.com/',
    Appliku: 'https://appliku.com/',
  },
  Learning: {
    JavaScriptInfo: 'https://javascript.info/',
    Educative: 'https://www.educative.io/explore',
    OdinProject: 'https://www.theodinproject.com',
    'Resilient Web Design': 'https://resilientwebdesign.com/',
    DjangoGirls: 'https://tutorial.djangogirls.org/en/',
  },
  CodeChallenges: {
    HackerRank: 'https://www.hackerrank.com/dashboard',
    CodeWars: 'https://www.codewars.com/dashboard',
    LeetCode: 'https://leetcode.com/problemset/all/',
    DevChallengesio: 'https://devchallenges.io/',
    FrontendMentor: 'https://www.frontendmentor.io/',
  },
  Ports: {
    'localhost://8000': 'http://localhost:8000/',
    'localhost://3000': 'http://localhost:3000/',
    'localhost://8080': 'http://localhost:8080/',
    'localhost://5050': 'http://localhost:5050/',
  },
  Haskell: {
    'Serokell Blog': 'https://serokell.io/blog/haskell',
    'Gutier Blog': 'https://gutier.io',
    'API Reference': 'https://hoogle.haskell.org',
  },
  Other: {
    GitExplorer: 'https://gitexplorer.com/',
    OhShitGit: 'https://ohshitgit.com/',
    GitMoji: 'https://gitmoji.dev/',
    'Javascipt AirBnB Styleguide': 'https://airbnb.io/javascript/',
    DjangoPackages: 'https://djangopackages.org/',
    DisStreamChat: 'https://www.disstreamchat.com/#/',
    PythonVisualise: 'http://pythontutor.com/visualize.html#mode=display',
    'Instagram # Generator': 'https://metahashtags.com/#',
    AnswerThePublic: 'https://answerthepublic.com/reports/1281666d-a597-4899-973e-4c7dc90bbb54',
    'Data Structures and Algos': 'https://www.tutorialspoint.com/data_structures_algorithms/stack_algorithm.htm',
    SpeedTyper: 'https://www.speedtyper.dev/',
    CountryGuesser: 'https://online.seterra.com/en/l/eur',
    BattleSnake: 'https://play.battlesnake.com/',
  },
};

export default links;
